- name: Include OS-specific variables
  include_vars: "{{ zj_distro_os }}"
  loop_control:
    loop_var: zj_distro_os
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution }}.{{ ansible_architecture }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"

- name: Check tox env for PDF build in tox.ini
  shell: |
    grep '^\[testenv:{{ tox_pdf_envlist }}\]' {{ zuul_work_dir }}/tox.ini
  register: pdfdocs_env
  ignore_errors: yes

- name: Install PDF prereqs
  package:
    name: "{{ zj_package }}"
    state: present
  become: yes
  loop: "{{ packages }}"
  loop_control:
    loop_var: zj_package
  when: pdfdocs_env is success
