---
- name: Install pip
  include_role:
    name: ensure-pip

- name: Install virtualenv
  include_role:
    name: ensure-virtualenv

# Installation of ansible in fresh venv is not possible until pip updates inside.
- name: Initialize venv
  pip:
    name: "pip"
    virtualenv: "{{ ensure_ansible_venv_path|default(omit, true) }}"

- name: Install Ansible
  pip:
    name: "{{ ensure_ansible_package_name|default('ansible-core', true) }}"
    version: "{{ ensure_ansible_version|default('latest', true) }}"
    state: "{{ ensure_ansible_state|default('present', true) }}"
    virtualenv: "{{ ensure_ansible_venv_path|default(omit, true) }}"
    extra_args: "{{ ensure_ansible_pip_extra_args|default(omit, true) }}"
    virtualenv_command: "{{ ensure_ansible_virtualenv_command|default(ensure_pip_virtualenv_command, true) | default(omit) }}"
    virtualenv_python: "{{ ensure_ansible_virtualenv_python|default(omit, true) }}"
    virtualenv_site_packages: "{{ ensure_ansible_virtualenv_site_packages|default(omit, true) }}"
  register: result

- name: >-
    Set ensure_ansible_ansible_executable and
    ensure_ansible_galaxy_executable
  set_fact:
    ensure_ansible_root_dir: "{{ result.virtualenv }}"
    ensure_ansible_ansible_executable: "{{ result.virtualenv }}/bin/ansible"
    ensure_ansible_galaxy_executable: "{{ result.virtualenv }}/bin/ansible-galaxy"
    cacheable: true

- name: Output Ansible version
  command: "{{ ensure_ansible_ansible_executable }} --version"
