ensure_gh_version: "2.9.0"
ensure_gh_download_uri: "https://github.com/cli/cli/releases/download/v{{ ensure_gh_version }}/gh_{{ ensure_gh_version }}_{{ ensure_gh_os }}_{{ ensure_gh_arch }}.tar.gz"
ensure_gh_os: "{{ ansible_system | lower }}"
ensure_gh_arch: "{{ gh_arch_translation[ansible_architecture] }}"
ensure_gh_install_dir: "/usr/local"
