---
terraform_executable: "{{ ansible_user_dir }}/.local/bin/terraform"
zuul_work_dir: "{{ zuul.project.src_dir }}"
zuul_examples_dir: "{{ zuul.project.src_dir }}/examples"
bucket_name: "tf-viz-pages"
insert_after: '<p class="navbar_github_main" hidden>HIDDEN</p>'
insert_line: |
  <a class="navbar_githubLink_main" href="/{{ zj_item }}/index.html">
  <p class="navbar_github_main">{{ zj_item | upper }} GRAPH</p>
  </a>
backend_bucket: "tf-viz-state"
backend_region: "eu-de"