---
terraform_executable: "{{ ansible_user_dir }}/.local/bin/terraform"
zuul_work_dir: "{{ zuul.project.src_dir }}"
zuul_examples_dir: "{{ zuul.project.src_dir }}/examples"
bucket_name: "tf-viz-pages"
insert_after: '<p class="navbar_github_main" hidden>HIDDEN</p>'
insert_line: |
  <div class="row">
  <div class="index_container_main">
  <a class="links_main" href="/{{ zj_item }}/index.html">{{ zj_item | upper }} GRAPH</a>
  </div>
  <div class="index_container_main">
  <details>
  <summary>
  SHOW CODE
  </summary>
  <pre>
  {{ hcl_content }}
  </pre>
  </details>
  </div>
  </div>
backend_bucket: "tf-viz-state"
backend_region: "eu-de"
state_name: "terraform.tfstate"
