---
terraform_executable: "{{ ansible_user_dir }}/.local/bin/terraform"
terraform_provider_repo: "https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud.git"
terraform_devel_path: "/tmp/provider"
terraform_git_version: "devel"
zuul_work_dir: "{{ zuul.project.src_dir }}"
zuul_examples_dir: "{{ zuul.project.src_dir }}/examples"
current_list: []
devel_list: []
bucket_name: "tf-viz-pages"
insert_after: '<p class="navbar_github_main" hidden>HIDDEN</p>'
insert_line: |
  <a class="navbar_githubLink_main" href="/{{ zj_item }}/index.html">
  <p class="navbar_github_main">{{ zj_item | upper }} GRAPH</p>
  </a>