---
- name: Terraform plan.json
  command: "{{ terraform_executable }} show -json plan.out"
  args:
    chdir: "{{ zuul_examples_dir }}/{{ zj_item }}"
  register: result
#  no_log: true

- name: Saving data to local file
  ansible.builtin.copy:
    content: "{{  result.stdout }}"
    dest: "{{ zuul_examples_dir }}/{{ zj_item }}/plan.json"
