---
- name: Check if link is already defined
  ansible.builtin.lineinfile:
    state: absent
    path: "{{ zuul_examples_dir }}/modules/main_page/index.html"
    search_string: "{{ zj_item }}"
  check_mode: true
  changed_when: false
  register: check

- name: Slurp main.tf file
  ansible.builtin.slurp:
    src: "{{ zuul_examples_dir }}/{{ zj_item }}/main.tf"
  register: hcl

- name: Get runtime
  set_fact:
    hcl_content: "{{ hcl.content | b64decode }}"

- name: Add link to index.html
  ansible.builtin.lineinfile:
    dest: "{{ zuul_examples_dir }}/modules/main_page/index.html"
    insertafter: "{{ insert_after }}"
    line: "{{ insert_line }}"
  when: check.found == 0

- name: Saving data to local file
  ansible.builtin.copy:
    src: "{{ zuul_examples_dir }}/modules/main_page/"
    remote_src: true
    dest: "/tmp/main_page/"
