---
- name: Initialize terraform
  command: "{{ terraform_executable }} init -no-color -input=false"
  args:
    chdir: "{{ zuul_examples_dir }}/modules/obs_upload"

- name: Index file lookup
  debug:
    msg: "{{ lookup('file', '{{ zuul_examples_dir }}/modules/main_page/index.html') }}"

- name: Terraform plan obs upload
  command: "{{ terraform_executable }} plan -var='bucket={{ bucket_name }}' -var='key={{ zj_item }}' -var='folder_path={{ zuul_examples_dir }}/{{ zj_item }}/terraform-visual-report' -var='index_path={{ zuul_examples_dir }}/modules/main_page'"
  args:
    chdir: "{{ zuul_examples_dir }}/modules/obs_upload"
  environment:
    "{{ viz_env | default(omit) }}"


- name: Terraform upload files to obs
  command: "{{ terraform_executable }} apply -auto-approve -var='bucket={{ bucket_name }}' -var='key={{ zj_item }}' -var='folder_path={{ zuul_examples_dir }}/{{ zj_item }}/terraform-visual-report' -var='index_path={{ zuul_examples_dir }}/modules/main_page'"
  args:
    chdir: "{{ zuul_examples_dir }}/modules/obs_upload"
  environment:
    "{{ viz_env | default(omit) }}"
