- hosts: all
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
    VAULT_TOKEN: "root"
  vars:
    secret_dest: "{{ ansible_user_dir }}/.vault_wrap_secret"
  roles:
    - ensure-vault
  tasks:
    - name: Start vault in dev mode
      command: "/usr/local/bin/vault server -dev -dev-root-token-id=root"
      async: 300
      poll: 0

    - name: Enable approle auth
      command: "/usr/local/bin/vault auth enable approle"

    - name: Create test approle
      command: "/usr/local/bin/vault write -f auth/approle/role/test"

    - name: Generate new secret for the role
      include_role:
        name: "create-vault-approle-secret"
      vars:
        vault_addr: "http://127.0.0.1:8200"
        vault_token: "root"
        vault_role_name: "test"
        vault_secret_dest: "{{ secret_dest }}"

    - name: Get content of the created secret
      slurp:
        src: "{{ secret_dest }}"
      register: secret

    - name: Debug created secret
      debug:
        msg: "{{ secret['content'] | b64decode }}"
