- name: Create tmp dir
  file:
    dest: "{{ tf_modules_tmp_dir }}"
    state: directory
    recurse: true

- name: Deploy data.json
  template:
    src: data.json.j2
    dest: "{{ tf_modules_tmp_dir }}/data.json"
    mode: 0644
  register: deploy

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: deploy
    verbosity: 4

- name: Publish a module
  ansible.builtin.uri:
    url: https://app.terraform.io/api/v2/organizations/my-organization/registry-modules
    headers:
      Content-Type: application/vnd.api+json
      Authorization: "Bearer {{ token }}"
    method: POST
    body: "{{ lookup('ansible.builtin.file','{{ tf_modules_tmp_dir }}/data.json') }}"
    force_basic_auth: true
    status_code: 201
    body_format: json
  vars:
    token: "{{ goreleaser_github_token.token | default(omit) }}"
  register: result

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: result
    verbosity: 4
