- name: Publish a module
  ansible.builtin.uri:
    url: https://app.terraform.io/api/v2/organizations/opentelekomcloud/registry-modules
    headers:
      Content-Type: application/vnd.api+json
      Authorization: "Bearer {{ tf_modules_token }}"
    method: POST
    force_basic_auth: true
    status_code: 201
    body_format: json
    body:
      data:
        type: "registry-modules"
        attributes:
          name: "{{ module_name | default('project-factory', true) }}"
          namespace: "opentelekomcloud"
          provider: "opentelekomcloud"
          registry-name: "public"
          no-code: true
  register: result

- name: Request result
  ansible.builtin.fail:
    msg: "{{ result }}"
