- name: Install podman
  package:
    name:
      - 'podman=3.4.4+ds1-1ubuntu1'
      - uidmap
      - slirp4netns
      - fuse-overlayfs
      - containernetworking-plugins
      # This enables container network dns resolution:
      - golang-github-containernetworking-plugin-dnsname
    state: present
  become: true

- name: Create containers config dir
  file:
    path: '{{ ansible_user_dir }}/.config/containers'
    state: directory
- name: Force cgroup manager to cgroupfs for Ubuntu
  copy:
    content: |
      [engine]
      cgroup_manager = "cgroupfs"
    dest: '{{ ansible_user_dir }}/.config/containers/containers.conf'
