---
- hosts: localhost
  vars:
    vault_addr: "{{ zuul_vault_addr }}"
    vault_secret_dest: "{{ zuul.executor.work_root }}/.approle-secret"
    vault_token_dest: "{{ zuul.executor.work_root }}/.approle-token"

  roles:
    # Get the Vault token from prepared secret-id
    - role: create-vault-approle-token
      vault_role_id: "{{ zuul_vault.vault_role_id }}"
      vault_wrapping_token_id: "{{ lookup('file', vault_secret_dest) }}"

- hosts: all
  vars:
    extra_vars_file: "{{ zuul.project.src_dir }}/extra_vars.yaml"
    playbook_file: "{{ ansible_user_dir }}/wrk/playbooks/gitstyring.yaml"
    log_file: "{{ ansible_user_dir }}/gitstyring.txt"
    vault_token_dest: "{{ zuul.executor.work_root }}/.approle-token"
    vault_addr: "{{ zuul_vault_addr }}"
  tasks:
    - name: Create extra_vars tempfile
      tempfile:
        state: file
      register: extra_vars_tmp

    - name: Set extra_vars
      no_log: true
      set_fact:
        extra_vars:
          vault:
            vault_token: "{{ lookup('file', vault_token_dest) }}"
            vault_addr: "{{ vault_addr }}"
            vault_token_path: "{{ zuul_vault.vault_token_path }}"
          gitcontrol_organizations: "{{ gitcontrol_organizations }}"
          gitcontrol_root_dir: "{{ gitcontrol_root_dir }}"
          git_type: "{{ gitcontrol_git_type | default('github') }}"
          api_url: "{{ gitcontrol_api_url | default(omit) }}"

    - name: Construct execution command
      set_fact:
        ansible_command: >-
          {{ ensure_ansible_ansible_executable }}-playbook
          {{ playbook_file }}
          -e "@{{ extra_vars_tmp.path }}"
          {{ check_mode | ternary('--check', '', '') }}
          -v

    - block:
        - name: Dump extra_vars
          copy:
            dest: "{{ extra_vars_tmp.path }}"
            content: "{{ extra_vars | to_nice_yaml }}"  # noqa jinja
            mode: "0600"

        - name: Log execution header
          shell: 'echo "Running {{ ansible_command }}" > {{ log_file }}'

        - name: Apply configuration
          shell: "{{ ansible_command }} >> {{ log_file }}"

      always:
        - name: Shred extra_vars file
          command: "shred {{ extra_vars_tmp.path }}"

        - name: Fetch log
          fetch:
            src: "{{ log_file }}"
            dest: "{{ zuul.executor.log_root }}/gitstyring.txt"
            flat: true
          failed_when: false
