- name: Check artifact
  stat:
    path: "{{ artifact_src }}"
  register: "artifact_stat"

- name: Upload artifact to swift
  no_log: true
  upload_artifact_swift:
    cloud: "{{ upload_artifact_swift_cloud }}"
    container: "{{ upload_artifact_swift_container_name }}"
    read_acl: "{{ upload_artifact_swift_container_read_acl }}"
    prefix: "{{ upload_artifact_swift_prefix }}"
    src: "{{ artifact_stat.stat.path }}"
