---
- job:
    name: project-cleanup
    description: |
      Perform OpenStack Project Cleanup to cleanup resources
    pre-run: playbooks/project_cleanup/pre.yaml
    run: playbooks/project_cleanup/run.yaml

- project:
    merge-mode: squash-merge
    default-branch: main
    templates:
      - publish-otc-docs-pti
