- name: Check {{ organization }} deneral data file
  ansible.builtin.stat:
    path: "{{ (gitcontrol_root_dir + '/' + organization + '/data.yaml') }}"
  register: org_data

- name: Read {{ organization }} organization target data
  include_vars:
    file: "{{ org_data.stat.path }}"
    name: "org"
  when: org_data.stat.exists

- name: Apply {{ organization }} members
  opentelekomcloud.gitcontrol.github_org_members:
    token: "{{ token }}"
    organization: "{{ organization }}"
    members: "{{ org.members }}"
    exclusive: "{{ org.exclusive | default(True) }}"
  when:
    - "org is defined"
    - "org.members is defined"
  register: members

- name: Apply {{ organization }} teams
  opentelekomcloud.gitcontrol.github_org_teams:
    token: "{{ token }}"
    organization: "{{ organization }}"
    teams: "{{ org.teams | default([]) }}"
    exclusive: "{{ org.exclusive | default(True) }}"
  when:
    - "org is defined"
    - "org.teams is defined"
  register: teams

- name: Find {{ organization }} repositories data
  ansible.builtin.find:
    paths: "{{ gitcontrol_root_dir + '/' + organization + '/repositories' }}"
    patterns: "*.yaml,*.yml"
    file_type: "file"
  register: repository_data

- include_tasks: "process_repository_file.yaml"
  vars:
    data: "{{ lookup('file', zj_repository_file.path) | from_yaml  }}"
  loop: "{{ repository_data.files }}"
  loop_control:
    loop_var: "zj_repository_file"
