---
upload_artifact_swift_prefix: ""
upload_artifact_swift_container_name: "{{ zuul.project.short_name }}"
upload_artifact_swift_container_public: true
upload_artifact_swift_container_read_acl: "{{ upload_artifact_swift_container_public | ternary('.r:*,.rlistings', omit, omit) }}"
