- hosts: all
  tasks:
    - name: Fetch tox output
      include_role:
        name: fetch-tox-output

    - name: Fetch sphinx tarball
      include_role:
        name: fetch-sphinx-tarball
      vars:
        sphinx_pdf_files: "{{ hostvars[inventory_hostname]['sphinx_pdf_files'] }}"

    - name: Fetch sphinx JSON
      include_role:
        name: fetch-sphinx-json
