- hosts: all
  roles:
    - revoke-sudo
    - tox
    - role: build-pdf-docs
      when: not tox_skip_pdf
  tasks:
    - block:
        # Build json output, but do not fail
        - name: Execute sphinx to generate JSON output
          include_role:
            name: sphinx
          vars:
            sphinx_builders: json
            zuul_work_virtualenv: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/.tox/{{ tox_envlist }}"

        - name: Drop irrelevant data from json output
          ansible.builtin.file:
            path: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/{{ sphinx_build_dir | default('doc/build') }}/json/{{ item }}"
            state: "absent"
          loop:
            - "_images"
            - "_static"
            - "_sources"
      ignore_errors: yes

    # Collect PDF files
    - name: Ensure the PDF directory exists
      stat:
        path: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/doc/build/pdf/"
      register: pdf_dir

    - name: Find all PDF files if the directory exists
      find:
        paths: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/doc/build/pdf/"
        patterns: "*.pdf"
        file_type: file
      when: pdf_dir.stat.exists
      register: pdf_files

    - name: Set fact for sphinx_pdf_files or an empty list
      set_fact:
        sphinx_pdf_files: "{{ pdf_files.files | default([]) | map(attribute='path') | map('basename') | list }}"
